version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis:6379
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: demtech_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app_network

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge