// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/emailstatsservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamal-github/demtech/internal/model"
)

// MockEmailsStatsGetter is a mock of EmailsStatsGetter interface.
type MockEmailsStatsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockEmailsStatsGetterMockRecorder
}

// MockEmailsStatsGetterMockRecorder is the mock recorder for MockEmailsStatsGetter.
type MockEmailsStatsGetterMockRecorder struct {
	mock *MockEmailsStatsGetter
}

// NewMockEmailsStatsGetter creates a new mock instance.
func NewMockEmailsStatsGetter(ctrl *gomock.Controller) *MockEmailsStatsGetter {
	mock := &MockEmailsStatsGetter{ctrl: ctrl}
	mock.recorder = &MockEmailsStatsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailsStatsGetter) EXPECT() *MockEmailsStatsGetterMockRecorder {
	return m.recorder
}

// GetEmailStats mocks base method.
func (m *MockEmailsStatsGetter) GetEmailStats(ctx context.Context) (model.EmailStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailStats", ctx)
	ret0, _ := ret[0].(model.EmailStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailStats indicates an expected call of GetEmailStats.
func (mr *MockEmailsStatsGetterMockRecorder) GetEmailStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailStats", reflect.TypeOf((*MockEmailsStatsGetter)(nil).GetEmailStats), ctx)
}
